### ISSUE TITLE
Add config file to save channel targets

### ISSUE THREAD

**Issue by ho0ber** [ho0ber/havomi#7]
Probably in AppData/Local - figure out the canonical way to do this in windows.

I'm imagining a YAML config much like the device configs:

```yaml
channels:
    1:
        type: ApplicationVolume
        name: Spotify.exe
    2:
        type: DeviceVolume
        name: Master
```
